#### Define a Bed reader and read a few values from it (they are a 2D numpy array)

In [10]:
import os
import numpy as np

from pysnptools.snpreader import Bed
snpreader = Bed("all.bed", count_A1=True)

# What is snpreader?
print(snpreader)
snpreader[:2,:4].read().val

Bed('all.bed',count_A1=True)


array([[0., 0., 1., 2.],
       [0., 0., 1., 1.]])

#### Convert a Bed reader into a distribution reader

In [4]:
from pysnptools.distreader import Snp2Dist
distreader = Snp2Dist(snpreader)
distreader

Snp2Dist(Bed('all.bed',count_A1=True))

#### Read a few values from the distribution reader. They are a 3D numpy array.

In [12]:
distdata = distreader[:2,:4].read()
distdata.val

array([[[1., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 1., 0.]]])

#### Write the distribution values to a file.

In [14]:
from pysnptools.distreader import DistMemMap
DistMemMap.write('sample.dist.memmap',distdata)

DistMemMap('sample.dist.memmap')

##### Read from the file. Listing the individual ID's the SNP id's and the values.

In [15]:
distmemmap = DistMemMap('sample.dist.memmap')
print(distmemmap.iid)
print(distmemmap.sid)
print(distmemmap.val)

[['cid0P0' 'cid0P0']
 ['cid1P0' 'cid1P0']]
['snp625_m0_.03m1_.07' 'snp1750_m0_.02m1_.04' 'snp0_m0_.37m1_.24'
 'snp375_m0_.52m1_.68']
[[[1. 0. 0.]
  [1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [1. 0. 0.]
  [0. 1. 0.]
  [0. 1. 0.]]]


#### Create an in-memory distribution
* Create via random
* Create a second distribution with the individuals reversed and with every 10th SNP.
* Print the start of the 2nd distribution's individual ID's the SNP id's and the values

In [22]:
from pysnptools.distreader import DistData
import numpy as np

np.random.seed(0)
iid_count = 100
sid_count = 1000
val = np.random.random((iid_count,sid_count,3))
val /= val.sum(axis=2,keepdims=True)  #make probabilities sum to 1
distdata = DistData(val=val,
                    iid=[('fam0','iid{0}'.format(i)) for i in range(iid_count)],
                    sid=['sid{0}'.format(s) for s in range(sid_count)]
                    )
distdata2 = distdata[::-1,::10].read()
print(distdata2.iid[:3])
print(distdata2.sid[:3])
print(distdata2.val[:3,:3])

[['fam0' 'iid99']
 ['fam0' 'iid98']
 ['fam0' 'iid97']]
['sid0' 'sid10' 'sid20']
[[[0.20081495 0.4737261  0.32545895]
  [0.52343568 0.16311684 0.31344748]
  [0.26296867 0.5548358  0.18219553]]

 [[0.29093073 0.36418333 0.34488594]
  [0.12887058 0.64865356 0.22247586]
  [0.00325359 0.69403215 0.30271426]]

 [[0.02445881 0.66399687 0.31154432]
  [0.33538909 0.35483828 0.30977264]
  [0.40125371 0.25403278 0.34471351]]]
